#include "tlpp-core.th"
#include "totvs.ch"

/*/{Protheus.doc} ZZ2GravaLog
Gravação de auditoria na tabela ZZ2
@type function
@version 1.0  
@author Pablo Regis
@since 9/24/2026
@param cRotina, character, rotina de origem da gravacao (ex.: MATA261)
@param cDocNum, character, numero do documento
@param cProduto, character, codigo do produto
@param nQuant, numeric, quantidade do produto
@param cArmOri, character, armazem de origem
@param cArmDes, character, armazem de destino
@param cJustificativa, character, justificativa da transferencia
@param cOrigem, character, origem da transferencia
@return logical, ".T. se o registro foi gravado com sucesso, ".F." caso contrario
/*/
User Function ZZ2GravaLog(cRotina, cDocNum, cProduto, nQuant, cArmOri, cArmDes, cJustificativa, cOrigem)
    Local aArea         := GetArea()               as Array
    Local lRet      := .T. as Logical

    Try

        DbSelectArea("ZZ2")
        DbSetOrder(1) 

        If RecLock("ZZ2", .T.)
            ZZ2->ZZ2_FILIAL  := xFilial("ZZ2")
            ZZ2->ZZ2_DOC     := cDocNum
            ZZ2->ZZ2_PRODUT  := cProduto
            ZZ2->ZZ2_QUANT   := nQuant
            ZZ2->ZZ2_ARMORI  := cArmOri
            ZZ2->ZZ2_ARMDES  := cArmDes
            ZZ2->ZZ2_ORIGEM  := cOrigem
            ZZ2->ZZ2_JUSTIF  := AllTrim(cJustificativa)
            ZZ2->ZZ2_USUARIO := Alltrim(UsrRetName(RetCodUsr()))
            ZZ2->ZZ2_DATA    := Date()
            ZZ2->ZZ2_HORA    := Time()            
            ZZ2->(MsUnlock())
        EndIf

    Catch oError
        RollbackSX8()
        FWLogMsg("ERROR", , "ZZ1GravaLog", cRotina, , "01", oError:Description, 0, 0, {})
        lRet := .F.
    EndTry

    RestArea(aArea)

Return lRet
